version: '3.8'

services:
  # 后端服务
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: helios_backend
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/helios
    depends_on:
      - db
    networks:
      - helios-network
    volumes:
      - ./backend:/app
      - ./logs:/app/logs
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  # 前端服务
  frontend:
    build:
      context: ./helios-frontend
      dockerfile: Dockerfile
    container_name: helios_frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - helios-network

  # 数据库服务
  db:
    image: postgres:15
    container_name: helios_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=helios
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - helios-network

networks:
  helios-network:
    driver: bridge

volumes:
  postgres_data:
